baseurl = "https://muzeeb-shaik.github.io/"
languageCode = "en-us"
title = "Muzeeb Shaik"
theme = "hugo-xmin"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmarkdown$", "_files$", "_cache$"]
footnotereturnlinkcontents = "↩"

[permalinks]
    post = "/post/:year/:month/:day/:slug/"
    note = "/note/:year/:month/:day/:slug/"

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

[[menu.main]]
    name = "Research"
    url = "/research/"
    weight = 2
[[menu.main]]
    name = "Teaching"
    url = "/teaching/"
    weight = 3
[[menu.main]]
    name = "CV"
    url = "/files/Muzeeb_Shaik_CV.pdf"
    weight = 4

[params]
    description = "Personal Webpage"
    footer = "&copy; [Muzeeb Shaik 2020](https://muzeeb-shaik.github.io/about)"
