---
title: "Some Information on Creating Websites with R"
author: "Harish Guda"
date: "2019-04-18"
output:
  blogdown::html_page:
    toc: true
    number_sections: true
    toc_depth: 1
slug: "website-info"
categories: 
  - "General"
tags: 
  - "Creating Websites"
  - "R"
---

Update: Much of this information is available in detail at multiple places, including:

- [The Little Dataset](https://thelittledataset.com/2018/08/26/let-me-upgrade-you/), 
- [Official Blogdown E-Book](https://bookdown.org/yihui/blogdown/), 
- [Alison Hill](https://alison.rbind.io/post/up-and-running-with-blogdown/#in-github) (who is a co-author on the textbook), 

among others.

I had previously owned a Google Site, which I never liked. I am quite comfortable with R, and when Yihui Xie and co-authors came out with the book on [blogdown](https://bookdown.org/yihui/blogdown/), I decided to try it. However, it can be still quite difficult with no experience to HTML, or prior exposure to CSS. Some useful tutorials from from the sources above eased my way into this beautiful package called blogdown. 

This webpage uses Yihui's [xmin](https://github.com/yihui/hugo-xmin) theme. What impressed me the most was how minimal the whole design of this website is. 

I deployed this website using Netlify. I bought a custom domain from Google Domains (~$20 a year?). 

I hope you find this useful if you plan to use it. 